version: '3'

services:
  db:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_user_pass
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 5s
      retries: 20
    ports:
      - "6033:3306"
    volumes:
      - dbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80

  symfony:
    build:
      context: ./symfony
      dockerfile: Dockerfile
    working_dir: /symfony
    container_name: symfony
    env_file:
      - ./.env
    links:
      - db
    volumes:
      - .:/var/www/html
    ports:
      - 8000:80
    depends_on:
      db:
        condition: service_healthy
    restart: always

  ngrok:
    image: shkoliar/ngrok:latest
    container_name: ngrok
    ports:
      - 4551:4551
    links:
      - symfony
    environment:
      - DOMAIN=symfony
      - PORT=80
      - REGION=eu
      - AUTH_TOKEN=2IE5CoyN8b8f9KuppFNkwUnLnby_6SSscyCX8nL3w5Lxqjstt

  project-configurator:
    build:
      context: ./projectconfigurator
      dockerfile: Dockerfile
    working_dir: /projectconfigurator
    container_name: projectconfigurator
    env_file:
      - ./.env
    volumes:
      - .:/usr/src/app
    restart: always

volumes:
  dbdata:
