version: '3'

services:
  db:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_user_pass
    ports:
      - "6033:3306"
    volumes:
      - dbdata:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
  symfony:
    build:
      context: ./
      dockerfile: Dockerfile
    working_dir: /
    container_name: symfony
    env_file:
      - ./docker/.env
    links:
      - db
    volumes:
      - .:/var/www/html
    ports:
      - 8000:80
    depends_on:
      - db
    restart: always
    ###> doctrine/doctrine-bundle ###
    #  database:
    #    image: postgres:${POSTGRES_VERSION:-14}-alpine
    #    environment:
    #      POSTGRES_DB: ${POSTGRES_DB:-app}
    # You should definitely change the password in production
    #      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
    #      POSTGRES_USER: ${POSTGRES_USER:-app}
    #    volumes:
    #      - db-data:/var/lib/postgresql/data:rw
    # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
    # - ./docker/db/data:/var/lib/postgresql/data:rw
    ###< doctrine/doctrine-bundle ###
volumes:
  dbdata:

    ###> doctrine/doctrine-bundle ###
    #  db-data:
    ###< doctrine/doctrine-bundle ###
