controllers:
    resource: ../src/Controller/
    type: attribute

# -------- Frontend --------

home:
    path: /
    controller: App\Controller\FrontendController::home

login:
    path: /login
    controller: App\Controller\FrontendController::login

# -------- Backend --------
 
loginInfo:
    path: /api/loginInfo
    controller: App\Controller\BackendController::loginInfo


sessionToken:
    path: /api/sessionToken
    controller: App\Controller\BackendController::sessionToken


passwordVerify:
    path: /api/passwordVerify
    controller: App\Controller\BackendController::passwordVerify