# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
  app.projectID: "%env(resolve:PROJECT_ID)%"
  app.apiSecret: "%env(resolve:API_SECRET)%"
  app.webhookUsername: "%env(resolve:WEBHOOK_USERNAME)%"
  app.webhookPassword: "%env(resolve:WEBHOOK_PASSWORD)%"

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  App\:
    resource: "../src/"
    exclude:
      - "../src/DependencyInjection/"
      - "../src/Entity/"
      - "../src/Kernel.php"

  # add more service definitions when explicit configuration is needed
  # please note that last definitions always *replace* previous ones

  Corbado\Client:
    autowire: true
    bind:
      $baseURI: "https://api.corbado.com"
      $username: "%app.projectID%"
      $password: "%app.apiSecret%"
