controllers:
    resource: ../src/Controller/
    type: attribute

# -------- Frontend --------

home:
    path: /
    controller: App\Controller\FrontendController::home

login:
    path: /login
    controller: App\Controller\FrontendController::login

pong:
    path: /ping
    controller: App\Controller\FrontendController::pong

# -------- Webhook --------

corbado:
    path: /corbado-webhook
    controller: App\Controller\WebhookController::corbado_webhook

# -------- Backend --------

sessionToken:
    path: /api/sessionToken
    controller: App\Controller\BackendController::sessionToken

# -------- Only required in this example --------

ngrokUrl:
    path: /api/ngrokUrl
    controller: App\Controller\BackendController::ngrokUrl